In [2]:
import numpy as np

In [5]:
x=np.arange(10).reshape(5,2)
y=range(5)


from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x , y)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

model.predict(x_test)

array([4., 1.])

In [9]:
x=np.arange(10).reshape(5,2)
y=range(5)


from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x , y)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
model.predict([[13,14]])

array([6.5])

In [13]:
import pickle


with open('LRmodel.pkl','wb')as f:
    pickle.dump(model,f)


In [16]:
with open('LRmodel.pkl','rb') as f:
    saved_model=pickle.load(f)

In [17]:
saved_model

LinearRegression()

In [22]:
saved_model.predict([[1000,1010]])

array([502.25])

In [23]:
import joblib

file='joblib_model.sav'
joblib.dump(model,file)


#Load model
joblib_model=joblib.load(file)

#predict values
joblib_model.predict([[10,11]])

array([5.])

In [25]:
import joblib

file='LR_model.sav'
joblib.dump(model,file)


#Load model
joblib_model=joblib.load(file)

#predict values
joblib_model.predict([[1,2]])

array([0.5])

In [ ]:
from flask import Flask,jsonify,request
import pickle

app = Flask(__name__)

@app.route('/')
def hello():
    return "Hello World"

@app.route('/input/<int:x1>/<int:x2>/')
def check(x1,x2):
    
    
    print(x1,"---",x2)
    fp=open('LRmodel.pkl',"rb")
    saved_model = pickle.load(fp)
    
    #pridect the output Y where input is x1 and x2 :
    predictedY = saved_model.predict([[x1,x2]])
    
    print("output is ",predictedY)
    return "Y : "+str(predictedY[0])


##########SERVER RUNNER#######################
#if__name__ == '_main_':
#    app.run(host='0.0.0.0', port=105)
app.run(host='0.0.0.0', port=106)

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:106
 * Running on http://192.168.172.170:106
Press CTRL+C to quit
127.0.0.1 - - [01/May/2024 13:19:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/May/2024 13:19:06] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [01/May/2024 13:19:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/May/2024 13:20:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/May/2024 13:20:28] "GET / HTTP/1.1" 200 -
